client:
	rm -f cl
	gcc client.c -o cl
	clear
	rm -f 127*.txt
	rm -f 127*.enc
	rm -f text*.enc
	./cl

server:
	rm -f sr
	gcc server.c -o sr
	clear
	./sr

clean:
	rm -f cl
	rm -f sr
	rm -f 127*.txt
	rm -f 127*.enc
	rm -f text*.enc